  
language: go

git:
  depth: 1

env:
  - GO111MODULE=on

go:
  - 1.12.x

before_install:
    - go get github.com/mattn/goveralls

script:
    goveralls -service=travis-ci

cache:
  directories:
    - /home/travis/gopath/pkg/mod
    - /home/travis/.cache/go-build

stages:
  - lint   
  - build
  - test
  - coverage

jobs:
  include:

    - stage: lint
      name: lint the go files
      script:
        - make lint 

    - stage: build
      name: Build binary
      script:
        - make

    - stage: test
      script:
        - make test

    - stage:
      name: coverage/coveralls 
      install:
        - go get golang.org/x/tools/cmd/cover
        - go get github.com/mattn/goveralls
      script:
        - make coverage
